### ISSUE TITLE
Bug on the demo.

### ISSUE THREAD

**Issue by jackdh** [desduvauchelle/react-hook-animate-number#2]
Setting the value to 5000000 hitting run, then set the value to 4000000 and hit run and the website crashes.

scheduler.production.min.js:12 
        
       Uncaught TypeError: o.toFixed is not a function
    at useAnimateNumber.tsx:53:31
    at Ui (react-dom.production.min.js:262:359)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ql (react-dom.production.min.js:122:325)
    at Ii (react-dom.production.min.js:261:308)
    at react-dom.production.min.js:261:215
    at D (scheduler.production.min.js:16:224)
    at k.port1.onmessage (scheduler.production.min.js:12:346)

Nice hook by the way!

**Comment by desduvauchelle** [comment]
Thanks. It's just a type issue. It's being passed a string instead of a number. Adding a failsafe in the library soon.

**Comment by desduvauchelle** [comment]
Fixed the typing issue and cleaned up the code a bit.
